### ISSUE TITLE
Erroneous warning on arg_fields

### ISSUE THREAD

**Issue by scjody** [replicatedhq/replicated-lint#69]
We're receiving the following lint error:

```
{ rule: 'prop-schema-valid',
  type: 'error',
  positions: 
   [ { path: 'config.15.items.3.test_proc.arg_field',
       start: { position: 29707, line: 758, column: 8 },
       end: { position: 29735, line: 760, column: 2 } } ],
  message: 'Unknown property (not in schema) [config.15.items.3.test_proc.arg_field]' }

# prop-schema-valid continued from line 753
754  
755      test_proc:
756          display_name: Validate JSON
757          command: validate_json
758          arg_field:
759          - json
```

`arg_field` appears to be valid based on the [documentation](https://help.replicated.com/docs/packaging-an-application/test-procs/#json-validation)

**Comment by dexhorthy** [comment]
Hi @scjody -- thanks for bringing this up, we'll investigate and address.

**Comment by dexhorthy** [comment]
Hi @scjody it looks like the option you're looking may be `arg_fields` -- can you try again with the `s` on the end?

**Comment by scjody** [comment]
@dexhorthy Oh, that's it. Sorry I missed that. The linter's doing its job!

**Comment by dexhorthy** [comment]
All good, thanks for giving it a spin, feedback always welcome!
