### ISSUE TITLE
Should this work with the kubernetes scheduler?

### ISSUE THREAD

**Issue by jhaynie** [replicatedhq/replicated-lint#73]
Doesn't seem to work when including the example Kubernetes Guest book example from the docs

```
{ type: 'error',
  rule: 'mesg-yaml-valid',
  message: 'expected a single document in the stream, but found more',
  positions: [] }
```

**Comment by dexhorthy** [comment]
Hi @jhaynie -- at the moment it only supports validating the Replicated-specific YAML document, you'll need to exclude any `# kind: scheduler-kubernetes` YAML documents before piping to `replicated-lint validate`.

This is a good question though, we're looking into providing support for not only built-in but also custom rules for your Kubernetes YAML specs.

**Comment by dexhorthy** [comment]
@jhaynie while replicated-lint doesn't natively support kubernetes, we've added an example project for defining and applying your own kubernetes rules at [projects/kubernetes](https://github.com/replicatedhq/replicated-lint/tree/master/projects/kubernetes)

**Comment by dexhorthy** [comment]
Closing - we can now lint kubernetes scheduler yaml in multidoc yaml files via `--doc <document index>` cli flag
